version: '3.9'
services:
  # MongoDB Servid
  mongo:
    container_name: mongo_db
    image: mongo:6.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  # Node
  node:
    build: .
    ports:
      - 5000:5000
    container_name: node_server
    image: server:18.12.0-alpine
    depends_on:
      - mongo
    external_links:
      - mongo
    volumes:
      - ./:/app
